import 'destination.dart';

class MockDestinations {
  static final List<Destination> items = [
    // -------------------------------------------------------------------------
    // TREKKING & HIKING (Existing entries updated with category)
    // -------------------------------------------------------------------------
    const Destination(
      id: 'dest_01',
      name: 'Valley of Flowers Trek',
      category: 'Trekking & Hiking',
      subType: 'Himalayan trek',
      activityTypes: ['trek', 'hike'],
      state: 'Uttarakhand',
      region: 'Garhwal Himalayas',
      lat: 30.7280,
      lng: 79.6053,
      difficulty: DifficultyLevel.moderate,
      durationDays: 6,
      altitudeMeters: 3858,
      terrainType: 'Alpine Meadow & River Valleys',
      description:
          'A UNESCO World Heritage Site renowned for its vibrant endemic alpine flora, cascading waterfalls, and misty snow-capped peaks. Nestled in the Chamoli district, this high-altitude valley blooms into a rainbow carpet from July to September.',
      photoUrls: [
        'https://picsum.photos/seed/valley_flowers_1/800/600',
        'https://picsum.photos/seed/valley_flowers_2/800/600',
      ],
      bestMonths: [7, 8, 9],
      avgRating: 4.8,
      reviewCount: 142,
    ),
    const Destination(
      id: 'dest_02',
      name: 'Kedarkantha Peak Trek',
      category: 'Trekking & Hiking',
      subType: 'Multi-day trek',
      activityTypes: ['trek', 'camping'],
      state: 'Uttarakhand',
      region: 'Uttarkashi / Sankri',
      lat: 31.0225,
      lng: 78.1726,
      difficulty: DifficultyLevel.moderate,
      durationDays: 5,
      altitudeMeters: 3800,
      terrainType: 'Pine Forests & Snow Ridge',
      description:
          'One of India\'s most popular winter summit treks. Offers a 360-degree panoramic view of Himalayan giants including Swargarohini, Bandarpoonch, and Black Peak from the summit.',
      photoUrls: [
        'https://picsum.photos/seed/kedarkantha_1/800/600',
      ],
      bestMonths: [12, 1, 2, 3, 4],
      avgRating: 4.7,
      reviewCount: 215,
    ),
    const Destination(
      id: 'dest_03',
      name: 'Roopkund Mystery Lake Trek',
      category: 'Trekking & Hiking',
      subType: 'Himalayan trek',
      activityTypes: ['trek'],
      state: 'Uttarakhand',
      region: 'Garhwal Himalayas',
      lat: 30.2644,
      lng: 79.7317,
      difficulty: DifficultyLevel.difficult,
      durationDays: 8,
      altitudeMeters: 5029,
      terrainType: 'High Altitude Snow Field & Glacial Lake',
      description:
          'A high-altitude glacial lake trek famous for the skeletal remains visible when ice thaws. Passes through Bedni and Ali Bugyal meadows.',
      photoUrls: [
        'https://picsum.photos/seed/roopkund_1/800/600',
      ],
      bestMonths: [5, 6, 9, 10],
      avgRating: 4.6,
      reviewCount: 98,
    ),
    const Destination(
      id: 'dest_04',
      name: 'Triund Trail',
      category: 'Trekking & Hiking',
      subType: 'Day hike',
      activityTypes: ['hike', 'camping'],
      state: 'Himachal Pradesh',
      region: 'Dharamshala / McLeod Ganj',
      lat: 32.2560,
      lng: 76.3530,
      difficulty: DifficultyLevel.easy,
      durationDays: 2,
      altitudeMeters: 2850,
      terrainType: 'Rhododendron Ridge & Oak Forest',
      description:
          'A tranquil short trek in the lap of the Dhauladhar range. Accessible from McLeod Ganj, offering sweeping views of Kangra Valley.',
      photoUrls: [
        'https://picsum.photos/seed/triund_1/800/600',
      ],
      bestMonths: [3, 4, 5, 9, 10, 11, 12],
      avgRating: 4.5,
      reviewCount: 320,
    ),
    const Destination(
      id: 'dest_05',
      name: 'Pin Parvati Pass Trek',
      category: 'Trekking & Hiking',
      subType: 'Himalayan trek',
      activityTypes: ['trek'],
      state: 'Himachal Pradesh',
      region: 'Kullu to Spiti Valley',
      lat: 31.9688,
      lng: 77.8631,
      difficulty: DifficultyLevel.expert,
      durationDays: 11,
      altitudeMeters: 5319,
      terrainType: 'Trans-Himalayan Glacier & Pass Crossing',
      description:
          'An exhilarating high-altitude pass connecting the lush Parvati Valley in Kullu with the cold desert valley of Spiti.',
      photoUrls: [
        'https://picsum.photos/seed/pin_parvati_1/800/600',
      ],
      bestMonths: [7, 8, 9],
      avgRating: 4.9,
      reviewCount: 45,
    ),
    const Destination(
      id: 'dest_06',
      name: 'Chembra Peak & Heart Lake',
      category: 'Trekking & Hiking',
      subType: 'Day hike',
      activityTypes: ['hike'],
      state: 'Kerala',
      region: 'Wayanad',
      lat: 11.5516,
      lng: 76.0898,
      difficulty: DifficultyLevel.easy,
      durationDays: 1,
      altitudeMeters: 2100,
      terrainType: 'Shola Grasslands & Tea Estates',
      description:
          'The highest peak in Wayanad features a natural heart-shaped lake (Hridayathadakam) halfway to the summit amid misty tea plantations.',
      photoUrls: [
        'https://picsum.photos/seed/chembra_1/800/600',
      ],
      bestMonths: [9, 10, 11, 12, 1, 2, 3],
      avgRating: 4.4,
      reviewCount: 168,
    ),

    // -------------------------------------------------------------------------
    // WILDLIFE & SAFARI EXPEDITIONS
    // -------------------------------------------------------------------------
    const Destination(
      id: 'dest_07',
      name: 'Kaziranga National Park',
      category: 'Wildlife & Safari Expeditions',
      subType: 'National park safari',
      activityTypes: ['safari'],
      state: 'Assam',
      region: 'Golaghat & Nagaon',
      lat: 26.5775,
      lng: 93.1711,
      difficulty: DifficultyLevel.easy,
      durationDays: 3,
      altitudeMeters: 80,
      terrainType: 'Tall Elephant Grass & Floodplain Wetlands',
      description:
          'Home to two-thirds of the world\'s great one-horned rhinoceroses. Features jeep and elephant safaris through Central, Western, and Eastern zones.',
      photoUrls: [
        'https://picsum.photos/seed/kaziranga_1/800/600',
      ],
      bestMonths: [11, 12, 1, 2, 3, 4],
      avgRating: 4.7,
      reviewCount: 190,
    ),
    const Destination(
      id: 'dest_08',
      name: 'Jim Corbett Tiger Reserve',
      category: 'Wildlife & Safari Expeditions',
      subType: 'National park safari',
      activityTypes: ['safari'],
      state: 'Uttarakhand',
      region: 'Nainital / Ramnagar',
      lat: 29.5300,
      lng: 78.7747,
      difficulty: DifficultyLevel.easy,
      durationDays: 3,
      altitudeMeters: 400,
      terrainType: 'Sal Forest & Ramganga River Basin',
      description:
          'India\'s oldest national park, famous for Royal Bengal tigers, wild elephants, gharials, and overnight stays inside Dhikala Forest Lodge.',
      photoUrls: [
        'https://picsum.photos/seed/corbett_1/800/600',
      ],
      bestMonths: [11, 12, 1, 2, 3, 4, 5, 6],
      avgRating: 4.6,
      reviewCount: 280,
    ),
    const Destination(
      id: 'dest_09',
      name: 'Gir Forest Asiatic Lion Sanctuary',
      category: 'Wildlife & Safari Expeditions',
      subType: 'National park safari',
      activityTypes: ['safari'],
      state: 'Gujarat',
      region: 'Junagadh District',
      lat: 21.1243,
      lng: 70.8242,
      difficulty: DifficultyLevel.easy,
      durationDays: 2,
      altitudeMeters: 150,
      terrainType: 'Dry Deciduous Forest & Teak Hills',
      description:
          'The sole remaining natural habitat of the endangered Asiatic Lion in the wild. Open gypsy safaris navigate through 8 designated jungle routes.',
      photoUrls: [
        'https://picsum.photos/seed/gir_1/800/600',
      ],
      bestMonths: [12, 1, 2, 3, 4, 5],
      avgRating: 4.5,
      reviewCount: 145,
    ),
    const Destination(
      id: 'dest_10',
      name: 'Sundarbans Mangrove Safari',
      category: 'Wildlife & Safari Expeditions',
      subType: 'Marine/coastal wildlife',
      activityTypes: ['safari', 'heritage'],
      state: 'West Bengal',
      region: 'South 24 Parganas',
      lat: 21.9497,
      lng: 88.9007,
      difficulty: DifficultyLevel.easy,
      durationDays: 3,
      altitudeMeters: 8,
      terrainType: 'Tidal Delta & Mangrove Estuary',
      description:
          'The world\'s largest mangrove forest delta. Navigate narrow creek waterways by boat to spot Royal Bengal tigers swimming between mudflat islands.',
      photoUrls: [
        'https://picsum.photos/seed/sundarbans_1/800/600',
      ],
      bestMonths: [11, 12, 1, 2, 3],
      avgRating: 4.5,
      reviewCount: 88,
    ),

    // -------------------------------------------------------------------------
    // CULTURAL IMMERSION TRIPS (New additions)
    // -------------------------------------------------------------------------
    const Destination(
      id: 'dest_cultural_01',
      name: 'Hampi Ancient Ruins & Temple Trail',
      category: 'Cultural Immersion Trips',
      subType: 'Heritage & monuments',
      activityTypes: ['heritage', 'pilgrimage'],
      state: 'Karnataka',
      region: 'Vijayanagara',
      lat: 15.3350,
      lng: 76.4600,
      terrainType: 'Bouldered Landscape & Temple Complex',
      description:
          'Step back into the 14th-century Vijayanagara Empire among colossal granite boulder hills, intricate stone chariots, Virupaksha temple rituals, and river coracle rides.',
      photoUrls: ['https://picsum.photos/seed/hampi_1/800/600'],
      bestMonths: [10, 11, 12, 1, 2, 3],
      avgRating: 4.9,
      reviewCount: 310,
      culturalHighlights: [
        'Vitthala Temple Stone Chariot',
        'Sunset over Hemakuta Hill',
        'Tungabhadra river coracle boat ride',
        'Royal Enclosure & Elephant Stables',
      ],
      familyFriendly: true,
      estimatedCostRange: '₹3,500 - ₹7,000 / person',
    ),
    const Destination(
      id: 'dest_cultural_02',
      name: 'Rajasthan Village & Craft Homestay Circuit',
      category: 'Cultural Immersion Trips',
      subType: 'Village homestays',
      activityTypes: ['heritage'],
      state: 'Rajasthan',
      region: 'Jodhpur & Pali Villages',
      lat: 26.2389,
      lng: 73.0243,
      terrainType: 'Rural Desert Outskirts',
      description:
          'Live with local Bishnoi and Rajput families. Learn traditional block printing, pottery, authentic Marwari vegetarian cooking, and evening folk music under open courtyards.',
      photoUrls: ['https://picsum.photos/seed/rajasthan_craft/800/600'],
      bestMonths: [10, 11, 12, 1, 2, 3],
      avgRating: 4.8,
      reviewCount: 124,
      culturalHighlights: [
        'Local terracotta pottery workshop',
        'Traditional Kalbelia folk dance performance',
        'Authentic Marwari Thali cooking class',
        'Bishnoi village wildlife sanctuary walk',
      ],
      familyFriendly: true,
      estimatedCostRange: '₹5,000 - ₹9,000 / person',
    ),
    const Destination(
      id: 'dest_cultural_03',
      name: 'Nagaland Hornbill Cultural Festival',
      category: 'Cultural Immersion Trips',
      subType: 'Festival tourism',
      activityTypes: ['heritage'],
      state: 'Nagaland',
      region: 'Kohima / Kisama Heritage Village',
      lat: 25.6751,
      lng: 94.1086,
      terrainType: 'Naga Hills & Tribal Village',
      description:
          'Known as the "Festival of Festivals". Experience 16 major Naga tribes coming together in colorful traditional regalia with warrior dances, indigenous games, and craft bazaars.',
      photoUrls: ['https://picsum.photos/seed/hornbill_1/800/600'],
      bestMonths: [12], // December 1-10
      avgRating: 4.9,
      reviewCount: 205,
      culturalHighlights: [
        '16 Tribal warrior dance performances',
        'Traditional Naga archery & log drum contests',
        'Naga King Chili eating competition',
        'Indigenous Morung architecture tours',
      ],
      familyFriendly: true,
      estimatedCostRange: '₹10,000 - ₹18,000 / person',
    ),
    const Destination(
      id: 'dest_cultural_04',
      name: 'Kerala Backwaters & Coir Craft Trail',
      category: 'Cultural Immersion Trips',
      subType: 'Craft & food trails',
      activityTypes: ['heritage'],
      state: 'Kerala',
      region: 'Alleppey & Kumarakom',
      lat: 9.4981,
      lng: 76.3388,
      terrainType: 'Coastal Lagoon & Canal Villages',
      description:
          'Glide along serene palm-fringed backwater canals in a traditional Kettuvallam houseboat. Visit village coir-weaving workshops, toddy shops, and organic spice farms.',
      photoUrls: ['https://picsum.photos/seed/kerala_craft/800/600'],
      bestMonths: [9, 10, 11, 12, 1, 2, 3],
      avgRating: 4.7,
      reviewCount: 240,
      culturalHighlights: [
        'Traditional Kettuvallam houseboat stay',
        'Coir coconut-fiber weaving demo',
        'Authentic Banana Leaf Keralite Sadya',
        'Kathakali performance at dusk',
      ],
      familyFriendly: true,
      estimatedCostRange: '₹6,500 - ₹14,000 / person',
    ),

    // -------------------------------------------------------------------------
    // WELLNESS & RELAXATION ESCAPES (New additions)
    // -------------------------------------------------------------------------
    const Destination(
      id: 'dest_wellness_01',
      name: 'Rishikesh Himalayan Yoga & Meditation Retreat',
      category: 'Wellness & Relaxation Escapes',
      subType: 'Yoga & meditation retreat',
      activityTypes: ['camping'],
      state: 'Uttarakhand',
      region: 'Rishikesh / Tapovan',
      lat: 30.1265,
      lng: 78.3243,
      terrainType: 'Ganges River Valley & Foothills',
      description:
          'Immerse in the Yoga Capital of the world. Daily sunrise Hatha & Vinyasa classes, Pranayama, Vedic chanting, Ganga Aarti, and Sattvic organic meals by the holy river.',
      photoUrls: ['https://picsum.photos/seed/rishikesh_yoga/800/600'],
      bestMonths: [9, 10, 11, 2, 3, 4],
      avgRating: 4.9,
      reviewCount: 340,
      wellnessFocus: 'Hatha Yoga & Ganga Pranayama',
      programSchedule: '7-day immersive program (Check-in every Monday)',
      familyFriendly: true,
      estimatedCostRange: '₹12,000 - ₹22,000 / person',
    ),
    const Destination(
      id: 'dest_wellness_02',
      name: 'Kerala Kovalam Ayurveda & Beach Spa',
      category: 'Wellness & Relaxation Escapes',
      subType: 'Ayurveda & spa',
      activityTypes: ['beach'],
      state: 'Kerala',
      region: 'Kovalam / Trivandrum',
      lat: 8.4004,
      lng: 76.9787,
      terrainType: 'Arabian Sea Beach & Coconut Palms',
      description:
          'Authentic Ayurvedic physician consultations, Abhyanga oil massages, Shirodhara head therapies, and oceanfront herbal steam baths.',
      photoUrls: ['https://picsum.photos/seed/kovalam_ayurveda/800/600'],
      bestMonths: [6, 7, 8, 9, 10, 11, 12, 1, 2, 3],
      avgRating: 4.8,
      reviewCount: 180,
      wellnessFocus: 'Panchakarma & Body Rejuvenation',
      programSchedule: '5-day & 14-day detox packages available',
      familyFriendly: true,
      estimatedCostRange: '₹15,000 - ₹35,000 / person',
    ),
    const Destination(
      id: 'dest_wellness_03',
      name: 'Coorg Rainforest Silent Meditation Retreat',
      category: 'Wellness & Relaxation Escapes',
      subType: 'Silent retreat',
      activityTypes: ['hike'],
      state: 'Karnataka',
      region: 'Kodagu / Madikeri',
      lat: 12.4244,
      lng: 75.7382,
      terrainType: 'Coffee Estate & Rainforest Canopies',
      description:
          'Disconnect from digital screens in a secluded coffee estate. Guided forest mindfulness walks (Shinrin-yoku), silent meals, and evening bell meditations.',
      photoUrls: ['https://picsum.photos/seed/coorg_wellness/800/600'],
      bestMonths: [9, 10, 11, 12, 1, 2, 3, 4],
      avgRating: 4.7,
      reviewCount: 95,
      wellnessFocus: 'Vipassana Silent Meditation & Forest Bathing',
      programSchedule: '3-day weekend quiet retreat',
      familyFriendly: false,
      estimatedCostRange: '₹8,000 - ₹15,000 / person',
    ),

    // -------------------------------------------------------------------------
    // ROAD TRIPS (New additions)
    // -------------------------------------------------------------------------
    const Destination(
      id: 'dest_road_01',
      name: 'Leh-Manali High-Pass Highway Drive',
      category: 'Road Trips',
      subType: 'Mountain pass drives',
      activityTypes: ['road_trip'],
      state: 'Himachal Pradesh & Ladakh',
      region: 'Manali to Leh',
      lat: 32.2432,
      lng: 77.1892,
      durationDays: 4,
      terrainType: 'High-Altitude Alpine Passes & River Canyons',
      description:
          'One of the ultimate adventure road trips in Asia. Traverse 479 km crossing Rohtang/Atal Tunnel, Baralacha La, Lachulung La, and Tanglang La passes.',
      photoUrls: ['https://picsum.photos/seed/leh_manali_road/800/600'],
      bestMonths: [6, 7, 8, 9],
      avgRating: 4.9,
      reviewCount: 420,
      routeDistanceKm: 479,
      suggestedStops: [
        'Manali Town',
        'Atal Tunnel North Portal',
        'Keylong / Jispa Valley',
        'Baralacha La Pass (4,890m)',
        'Sarchu Campsite',
        'Tanglang La Pass (5,328m)',
        'Leh City',
      ],
      familyFriendly: true,
      estimatedCostRange: '₹14,000 - ₹28,000 / vehicle',
    ),
    const Destination(
      id: 'dest_road_02',
      name: 'Mumbai to Goa Coastal Highway (NH 66)',
      category: 'Road Trips',
      subType: 'Coastal drives',
      activityTypes: ['road_trip', 'beach'],
      state: 'Maharashtra & Goa',
      region: 'Konkan Coastline',
      lat: 18.9401,
      lng: 72.8347,
      durationDays: 3,
      terrainType: 'Winding Coastal Ridges & Estuary Bridges',
      description:
          'Drive along the scenic Konkan coastline hugging the Arabian Sea. Enjoy cashew orchards, sea forts like Murud-Janjira & Sindhudurg, and fresh seafood shacks.',
      photoUrls: ['https://picsum.photos/seed/mumbai_goa_drive/800/600'],
      bestMonths: [10, 11, 12, 1, 2, 3],
      avgRating: 4.8,
      reviewCount: 290,
      routeDistanceKm: 580,
      suggestedStops: [
        'Mumbai Gate of India',
        'Alibaug Beach',
        'Murud Janjira Sea Fort',
        'Ganpatipule Temple Beach',
        'Tarkarli Scuba Bay',
        'Panaji Waterfront Goa',
      ],
      familyFriendly: true,
      estimatedCostRange: '₹8,000 - ₹16,000 / vehicle',
    ),
    const Destination(
      id: 'dest_road_03',
      name: 'Great Rann of Kutch Desert Circuit',
      category: 'Road Trips',
      subType: 'Desert circuits',
      activityTypes: ['road_trip', 'heritage'],
      state: 'Gujarat',
      region: 'Kutch / Bhuj',
      lat: 23.2420,
      lng: 69.6669,
      durationDays: 3,
      terrainType: 'White Salt Desert & Flat Salt Marshes',
      description:
          'Drive across the endless white salt desert expanse. Visit the highest point at Kala Dungar, craft villages in Nirona, and full moon night views over the salt flats.',
      photoUrls: ['https://picsum.photos/seed/rann_kutch_drive/800/600'],
      bestMonths: [11, 12, 1, 2],
      avgRating: 4.7,
      reviewCount: 170,
      routeDistanceKm: 350,
      suggestedStops: [
        'Bhuj Prag Mahal Palace',
        'Nirona Rogan Art Village',
        'Dhordo White Desert Tent City',
        'Kala Dungar (Black Hill)',
        'Mandvi Shipbuilding Yard & Beach',
      ],
      familyFriendly: true,
      estimatedCostRange: '₹7,000 - ₹15,000 / vehicle',
    ),
  ];
}
