import 'destination.dart';

class MockDestinations {
  static final List<Destination> items = [
    const Destination(
      id: 'dest_01',
      name: 'Valley of Flowers Trek',
      activityTypes: ['trek', 'hike'],
      state: 'Uttarakhand',
      region: 'Garhwal Himalayas',
      lat: 30.7280,
      lng: 79.6053,
      difficulty: DifficultyLevel.moderate,
      durationDays: 6,
      altitudeMeters: 3858,
      terrainType: 'Alpine Meadow & River Valleys',
      description:
          'A UNESCO World Heritage Site renowned for its vibrant endemic alpine flora, cascading waterfalls, and misty snow-capped peaks. Nestled in the Chamoli district, this high-altitude valley blooms into a rainbow carpet from July to September.',
      photoUrls: [
        'https://picsum.photos/seed/valley_flowers_1/800/600',
        'https://picsum.photos/seed/valley_flowers_2/800/600',
        'https://picsum.photos/seed/valley_flowers_3/800/600',
      ],
      bestMonths: [7, 8, 9], // July - September
      avgRating: 4.8,
      reviewCount: 142,
      permitInfo:
          'Forest Department permit mandatory (₹200 per head for Indians, ₹800 for foreigners). Available at Nanda Devi National Park gate in Ghangaria.',
      nearestHospital:
          'Army Base Hospital, Joshimath (~45km from Govindghat base).',
      networkCoverage:
          'BSNL & Jio work till Govindghat. Zero signal past Ghangaria base camp.',
      estimatedCostRange: '₹8,500 - ₹12,000 / person',
      mockReviews: [
        DestinationReview(
          authorName: 'Ananya Sharma',
          rating: 5.0,
          dateStr: 'August 2025',
          reviewText:
              'Incredible explosion of colors in August! The climb from Govindghat to Ghangaria is paved, but carry rain poncho.',
        ),
        DestinationReview(
          authorName: 'Rohan Verma',
          rating: 4.5,
          dateStr: 'July 2025',
          reviewText:
              'Breathtaking views. Hemkund Sahib detour is steep but worth every step.',
        ),
      ],
    ),
    const Destination(
      id: 'dest_02',
      name: 'Kedarkantha Peak Trek',
      activityTypes: ['trek', 'camping'],
      state: 'Uttarakhand',
      region: 'Uttarkashi / Sankri',
      lat: 31.0225,
      lng: 78.1726,
      difficulty: DifficultyLevel.moderate,
      durationDays: 5,
      altitudeMeters: 3800,
      terrainType: 'Pine Forests & Snow Ridge',
      description:
          'One of India\'s most popular winter summit treks. Offers a 360-degree panoramic view of Himalayan giants including Swargarohini, Bandarpoonch, and Black Peak from the summit.',
      photoUrls: [
        'https://picsum.photos/seed/kedarkantha_1/800/600',
        'https://picsum.photos/seed/kedarkantha_2/800/600',
        'https://picsum.photos/seed/kedarkantha_3/800/600',
      ],
      bestMonths: [12, 1, 2, 3, 4], // Winter snow trek
      avgRating: 4.7,
      reviewCount: 215,
      hasActiveAlert: true,
      activeAlertText:
          'WEATHER ADVISORY: Heavy snowfall expected near summit ridge. Microspikes & gaiters mandatory beyond Juda-ka-Talab.',
      permitInfo:
          'Govt & Forest permits collected at Sankri Base Camp checkpoint (₹150 per person).',
      nearestHospital:
          'Community Health Centre, Purola (~55km from Sankri base).',
      networkCoverage:
          'BSNL & Airtel available in Sankri village. No signal above Juda-ka-Talab campsite.',
      estimatedCostRange: '₹6,000 - ₹9,500 / person',
      mockReviews: [
        DestinationReview(
          authorName: 'Vikramaditya Roy',
          rating: 5.0,
          dateStr: 'January 2026',
          reviewText:
              'Summit day sunrise was unreal! Watching the snow turn golden on Bandarpoonch was magical.',
        ),
        DestinationReview(
          authorName: 'Priya Nair',
          rating: 4.0,
          dateStr: 'December 2025',
          reviewText:
              'Sub-zero temperatures at night. Make sure to pack proper -10°C rated sleeping bags.',
        ),
      ],
    ),
    const Destination(
      id: 'dest_03',
      name: 'Chopta, Chandrashila & Tungnath',
      activityTypes: ['trek', 'pilgrimage', 'hike'],
      state: 'Uttarakhand',
      region: 'Rudraprayag',
      lat: 30.4878,
      lng: 79.2189,
      difficulty: DifficultyLevel.easy,
      durationDays: 3,
      altitudeMeters: 4000,
      terrainType: 'Rhododendron Meadows & Ridge Trail',
      description:
          'Known as the "Mini Switzerland of India", Chopta is the base for Tungnath—the highest Shiva temple in the world—and the towering Chandrashila summit with vistas of Nanda Devi.',
      photoUrls: [
        'https://picsum.photos/seed/chopta_1/800/600',
        'https://picsum.photos/seed/chopta_2/800/600',
      ],
      bestMonths: [3, 4, 5, 10, 11, 12],
      avgRating: 4.9,
      reviewCount: 180,
      permitInfo: 'No special permits required. Eco-tax of ₹50 collected at Chopta market entry.',
      nearestHospital: 'District Hospital, Gopeshwar (~40km).',
      networkCoverage: 'Jio 4G works at Chopta market. Weak on Chandrashila peak.',
      estimatedCostRange: '₹4,500 - ₹7,000 / person',
      mockReviews: [
        DestinationReview(
          authorName: 'Kavita Patel',
          rating: 5.0,
          dateStr: 'May 2025',
          reviewText:
              'Red rhododendrons in full bloom along the trail to Tungnath. Very doable for beginners!',
        ),
      ],
    ),
    const Destination(
      id: 'dest_04',
      name: 'Hampi Heritage Trail',
      activityTypes: ['heritage', 'hike'],
      state: 'Karnataka',
      region: 'Vijayanagara',
      lat: 15.3350,
      lng: 76.4600,
      difficulty: DifficultyLevel.easy,
      durationDays: 3,
      altitudeMeters: 467,
      terrainType: 'Boulder Hills & Riverfront Ruins',
      description:
          'Step back in time to the 14th-century capital of the Vijayanagara Empire. Explore iconic stone chariots, royal enclosures, and boulder-strewn landscapes along the Tungabhadra River.',
      photoUrls: [
        'https://picsum.photos/seed/hampi_1/800/600',
        'https://picsum.photos/seed/hampi_2/800/600',
      ],
      bestMonths: [10, 11, 12, 1, 2, 3],
      avgRating: 4.8,
      reviewCount: 310,
      permitInfo: 'ASI combined ticket ₹40 (Indians) / ₹600 (Foreigners) for Vittala & Zenana Enclosures.',
      nearestHospital: 'District Hospital, Hosapete (~12km).',
      networkCoverage: 'Strong 4G coverage across all main monument zones.',
      estimatedCostRange: '₹3,500 - ₹6,500 / person',
    ),
    const Destination(
      id: 'dest_05',
      name: 'Jog Falls & Sharavathi Valley',
      activityTypes: ['hike', 'heritage'],
      state: 'Karnataka',
      region: 'Shivamogga',
      lat: 14.2285,
      lng: 74.8116,
      difficulty: DifficultyLevel.easy,
      durationDays: 2,
      altitudeMeters: 480,
      terrainType: 'Rainforest Steps & River Gorge',
      description:
          'Experience India\'s second-highest plunge waterfall. The Sharavathi River drops 253 meters in four distinct cascades: Raja, Roarer, Rocket, and Rani.',
      photoUrls: [
        'https://picsum.photos/seed/jogfalls_1/800/600',
      ],
      bestMonths: [8, 9, 10, 11, 12],
      avgRating: 4.5,
      reviewCount: 95,
    ),
    const Destination(
      id: 'dest_06',
      name: 'Spiti Valley Circuit',
      activityTypes: ['road_trip', 'camping', 'heritage'],
      state: 'Himachal Pradesh',
      region: 'Lahaul & Spiti',
      lat: 32.2461,
      lng: 78.0349,
      difficulty: DifficultyLevel.difficult,
      durationDays: 8,
      altitudeMeters: 4270,
      terrainType: 'High Altitude Cold Desert',
      description:
          'A high-mountain cold desert valley known for ancient Tibetan Buddhist monasteries like Key & Dhankar, high passes (Kunzum La), turquoise lakes (Chandratal), and starry nights.',
      photoUrls: [
        'https://picsum.photos/seed/spiti_1/800/600',
        'https://picsum.photos/seed/spiti_2/800/600',
      ],
      bestMonths: [6, 7, 8, 9],
      avgRating: 4.9,
      reviewCount: 275,
      permitInfo: 'Inner Line Permit mandatory for foreign nationals visiting Tabo & Nako.',
      nearestHospital: 'Mission Hospital, Kaza (~20km).',
      networkCoverage: 'BSNL post-paid works in Kaza. Zero connectivity near Chandratal.',
      estimatedCostRange: '₹14,000 - ₹22,000 / person',
    ),
    const Destination(
      id: 'dest_07',
      name: 'Triund Trail',
      activityTypes: ['trek', 'camping'],
      state: 'Himachal Pradesh',
      region: 'Dharamshala / McLeod Ganj',
      lat: 32.2472,
      lng: 76.3533,
      difficulty: DifficultyLevel.easy,
      durationDays: 2,
      altitudeMeters: 2850,
      terrainType: 'Oak & Deodar Forest Crest',
      description:
          'A ridge trail offering spectacular views of the snow-clad Dhauladhar range on one side and the Kangra Valley on the other. Ideal for weekend hikers and first-time campers.',
      photoUrls: [
        'https://picsum.photos/seed/triund_1/800/600',
      ],
      bestMonths: [3, 4, 5, 9, 10, 11, 12],
      avgRating: 4.6,
      reviewCount: 190,
    ),
    const Destination(
      id: 'dest_08',
      name: 'Jim Corbett National Park Safari',
      activityTypes: ['safari', 'camping'],
      state: 'Uttarakhand',
      region: 'Nainital District',
      lat: 29.5300,
      lng: 78.7747,
      difficulty: DifficultyLevel.easy,
      durationDays: 3,
      altitudeMeters: 400,
      terrainType: 'Sal Forest & Grasslands',
      description:
          'India\'s oldest national park, famous for Bengal tigers, wild elephants, and rich avian fauna along the Ramganga River in the Himalayan foothills.',
      photoUrls: [
        'https://picsum.photos/seed/corbett_1/800/600',
      ],
      bestMonths: [11, 12, 1, 2, 3, 4, 5, 6],
      avgRating: 4.7,
      reviewCount: 220,
    ),
    const Destination(
      id: 'dest_09',
      name: 'Palolem & Butterfly Beach',
      activityTypes: ['beach', 'hike'],
      state: 'Goa',
      region: 'South Goa',
      lat: 15.0100,
      lng: 74.0230,
      difficulty: DifficultyLevel.easy,
      durationDays: 3,
      altitudeMeters: 15,
      terrainType: 'Coastal Sand & Cliff Trail',
      description:
          'Crescent-shaped white sand beach lined with coconut palms. Take a boat or hike through forest trails to secluded Butterfly Beach and Monkey Island.',
      photoUrls: [
        'https://picsum.photos/seed/palolem_1/800/600',
      ],
      bestMonths: [11, 12, 1, 2, 3],
      avgRating: 4.8,
      reviewCount: 165,
    ),
    const Destination(
      id: 'dest_10',
      name: 'Ranthambore Tiger Reserve',
      activityTypes: ['safari'],
      state: 'Rajasthan',
      region: 'Sawai Madhopur',
      lat: 26.0173,
      lng: 76.5026,
      difficulty: DifficultyLevel.easy,
      durationDays: 3,
      altitudeMeters: 250,
      terrainType: 'Dry Deciduous Forest & Fort Ruins',
      description:
          'Historic hunting grounds of Maharajas surrounding 10th-century Ranthambore Fort. World famous for daytime tiger sightings near ancient ruins.',
      photoUrls: [
        'https://picsum.photos/seed/ranthambore_1/800/600',
      ],
      bestMonths: [10, 11, 12, 1, 2, 3, 4, 5],
      avgRating: 4.7,
      reviewCount: 140,
    ),
    const Destination(
      id: 'dest_11',
      name: 'Jaisalmer Sand Dunes Expedition',
      activityTypes: ['camping', 'road_trip'],
      state: 'Rajasthan',
      region: 'Thar Desert',
      lat: 26.9157,
      lng: 70.9083,
      difficulty: DifficultyLevel.easy,
      durationDays: 3,
      altitudeMeters: 225,
      terrainType: 'Sand Dunes & Desert Scrub',
      description:
          'Experience the golden sands of Sam & Khuri. Enjoy camel safaris, quad biking, sunset folk music performances, and luxury glamping under clear desert skies.',
      photoUrls: [
        'https://picsum.photos/seed/jaisalmer_1/800/600',
      ],
      bestMonths: [10, 11, 12, 1, 2, 3],
      avgRating: 4.6,
      reviewCount: 130,
    ),
    const Destination(
      id: 'dest_12',
      name: 'Cherrapunji Living Root Bridges',
      activityTypes: ['hike', 'trek'],
      state: 'Meghalaya',
      region: 'East Khasi Hills',
      lat: 25.2986,
      lng: 91.5822,
      difficulty: DifficultyLevel.difficult,
      durationDays: 4,
      altitudeMeters: 1484,
      terrainType: 'Subtropical Rainforest & Stepped Canyon',
      description:
          'Trek down 3,500 stone steps into the lush jungle to behold double-decker living root bridges handcrafted by Khasi tribes over centuries from rubber fig trees.',
      photoUrls: [
        'https://picsum.photos/seed/cherrapunji_1/800/600',
      ],
      bestMonths: [10, 11, 12, 1, 2, 3, 4, 5],
      avgRating: 4.9,
      reviewCount: 175,
    ),
    const Destination(
      id: 'dest_13',
      name: 'Varkala Cliff & Edava Beach',
      activityTypes: ['beach', 'pilgrimage'],
      state: 'Kerala',
      region: 'Thiruvananthapuram',
      lat: 8.7379,
      lng: 76.7163,
      difficulty: DifficultyLevel.easy,
      durationDays: 3,
      altitudeMeters: 30,
      terrainType: 'Red Laterite Cliff & Arabian Sea Coast',
      description:
          'Unique red laterite cliffs bordering the Arabian Sea. Renowned for natural mineral springs, cliffside cafes, sunset views, and Janardanaswamy Temple.',
      photoUrls: [
        'https://picsum.photos/seed/varkala_1/800/600',
      ],
      bestMonths: [10, 11, 12, 1, 2, 3],
      avgRating: 4.8,
      reviewCount: 155,
    ),
    const Destination(
      id: 'dest_14',
      name: 'Hemis Monastery & High Pass Trail',
      activityTypes: ['pilgrimage', 'trek'],
      state: 'Ladakh',
      region: 'Leh District',
      lat: 33.9125,
      lng: 77.7011,
      difficulty: DifficultyLevel.expert,
      durationDays: 7,
      altitudeMeters: 4400,
      terrainType: 'High Altitude Trans-Himalayan Valley',
      description:
          'Home to the 17th-century Drukpa lineage monastery famous for its annual Tsechu mask festival and high-altitude wildlife trail home to the elusive snow leopard.',
      photoUrls: [
        'https://picsum.photos/seed/hemis_1/800/600',
      ],
      bestMonths: [6, 7, 8, 9],
      avgRating: 4.9,
      reviewCount: 110,
    ),
    const Destination(
      id: 'dest_15',
      name: 'Sundarbans Mangrove Safari',
      activityTypes: ['safari', 'heritage'],
      state: 'West Bengal',
      region: 'South 24 Parganas',
      lat: 21.9497,
      lng: 88.9007,
      difficulty: DifficultyLevel.easy,
      durationDays: 3,
      altitudeMeters: 8,
      terrainType: 'Tidal Delta & Mangrove Estuary',
      description:
          'The world\'s largest mangrove forest delta. Navigate narrow creek waterways by boat to spot Royal Bengal tigers swimming between mudflat islands.',
      photoUrls: [
        'https://picsum.photos/seed/sundarbans_1/800/600',
      ],
      bestMonths: [11, 12, 1, 2, 3],
      avgRating: 4.5,
      reviewCount: 88,
    ),
  ];
}
